In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score
from sklearn.ensemble import RandomForestClassifier

In [3]:
df = pd.read_csv("../DATA/PROCESS/save_dataset3.csv")

In [4]:
df.drop(columns=["Unnamed: 0.1", "Unnamed: 0"], inplace=True)

## Random Test

In [ ]:
# # 1. 기본 세팅

# target_col = "target"

# drop_cols = [
#     target_col,
#     "datetime",
# ]

# drop_cols = [col for col in drop_cols if col in df.columns]

# X = df.drop(columns=drop_cols)
# y = df[target_col]

# print("X shape:", X.shape)
# print("y distribution:")
# print(y.value_counts(normalize=True))


# # 2. 컬럼 타입 분리


# categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
# numeric_cols = X.select_dtypes(include=["int64", "float64", "int32", "float32"]).columns.tolist()

# print("numeric cols:", len(numeric_cols))
# print("categorical cols:", len(categorical_cols))

# # 3. 전처리 파이프라인

# numeric_transformer = Pipeline(steps=[
#     ("imputer", SimpleImputer(strategy="median")),
#     ("scaler", StandardScaler())
# ])

# categorical_transformer = Pipeline(steps=[
#     ("imputer", SimpleImputer(strategy="most_frequent")),
#     ("onehot", OneHotEncoder(handle_unknown="ignore"))
# ])

# preprocessor = ColumnTransformer(
#     transformers=[
#         ("num", numeric_transformer, numeric_cols),
#         ("cat", categorical_transformer, categorical_cols),
#     ]
# )

# # 4. Train/Test split

# X_train, X_test, y_train, y_test = train_test_split(
#     X,
#     y,
#     test_size=0.2,
#     random_state=42,
#     stratify=y
# )

# print("train target distribution:")
# print(y_train.value_counts(normalize=True))

# print("test target distribution:")
# print(y_test.value_counts(normalize=True))

# # 5. 모델 학습

# model = Pipeline(steps=[
#     ("preprocess", preprocessor),
#     ("clf", RandomForestClassifier(
#         n_estimators=300,
#         random_state=42,
#         class_weight="balanced",
#         n_jobs=-1
#     ))
# ])

# model.fit(X_train, y_train)

# # 6. 예측 및 평가

# y_pred = model.predict(X_test)
# y_proba = model.predict_proba(X_test)[:, 1]

# print("\nClassification Report")
# print(classification_report(y_test, y_pred, digits=4))

# print("\nConfusion Matrix")
# print(confusion_matrix(y_test, y_pred))

# print("\nROC-AUC")
# print(roc_auc_score(y_test, y_proba))

X shape: (4033906, 97)
y distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64
numeric cols: 95
categorical cols: 2

/var/folders/g8/gwqmqng10_g3h7m8r02yq1qc0000gn/T/ipykernel_74879/1362361736.py:23: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()

train target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64
test target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

KeyboardInterrupt:

In [ ]:
# # 7. Feature Importance 확인

# rf = model.named_steps["clf"]

# feature_names = model.named_steps["preprocess"].get_feature_names_out()

# importance_df = pd.DataFrame({
#     "feature": feature_names,
#     "importance": rf.feature_importances_
# }).sort_values("importance", ascending=False)

# importance_df.head(30)

                                feature  importance
3                             num__hour    0.127907
7                         num__hour_cos    0.078663
6                         num__hour_sin    0.063019
42                   num__rest_cnt_500m    0.054801
43                  num__rest_cnt_1000m    0.029487
41                   num__rest_cnt_300m    0.029143
85       num__subway_weighted_access_k5    0.027568
86           num__subway_mean_dist_k5_m    0.022304
12                    num__gu_walk_area    0.019071
53       num__tour_food_mean_dist_k20_m    0.017638
84           num__nearest_subway_dist_m    0.017374
62            num__shop_mean_dist_k20_m    0.017322
76               num__bus_stop_cnt_300m    0.017241
71                   num__shop_type_cnt    0.015221
40                   num__rest_cnt_100m    0.014345
61       num__shop_weighted_density_k20    0.014343
73               num__shop_type_entropy    0.013941
2                               num__경도    0.013169
1                               num__위도    0.013036
44             num__nearest_rest_dist_m    0.013020
17                     num__concert_mid    0.013010
52  num__tour_food_weighted_density_k20    0.012960
79               num__bus_stop_cnt_500m    0.012759
60             num__nearest_shop_dist_m    0.012658
82                num__subway_cnt_1000m    0.012314
51        num__nearest_tour_food_dist_m    0.011217
4                          num__weekday    0.011101
14                  num__concert_public    0.011016
88       num__subway_line_entropy_1000m    0.010812
8                      num__weekday_sin    0.010796

## Time Test

In [ ]:
# df = df.sort_values("datetime")

# split_idx = int(len(df) * 0.8)

# X_train = X.iloc[:split_idx]
# X_test = X.iloc[split_idx:]

# y_train = y.iloc[:split_idx]
# y_test = y.iloc[split_idx:]

In [ ]:
# print("train target distribution:")
# print(y_train.value_counts(normalize=True))

# print("test target distribution:")
# print(y_test.value_counts(normalize=True))

# # 5. 모델 학습

# model = Pipeline(steps=[
#     ("preprocess", preprocessor),
#     ("clf", RandomForestClassifier(
#         n_estimators=300,
#         random_state=42,
#         class_weight="balanced",
#         n_jobs=-1
#     ))
# ])

# model.fit(X_train, y_train)

# # 6. 예측 및 평가

# y_pred = model.predict(X_test)
# y_proba = model.predict_proba(X_test)[:, 1]

# print("\nClassification Report")
# print(classification_report(y_test, y_pred, digits=4))

# print("\nConfusion Matrix")
# print(confusion_matrix(y_test, y_pred))

# print("\nROC-AUC")
# print(roc_auc_score(y_test, y_proba))

train target distribution:
target
0    0.578189
1    0.421811
Name: proportion, dtype: float64
test target distribution:
target
1    0.58939
0    0.41061
Name: proportion, dtype: float64

Classification Report
              precision    recall  f1-score   support

           0     0.3943    0.7289    0.5117     30365
           1     0.5378    0.2198    0.3120     43586

    accuracy                         0.4288     73951
   macro avg     0.4661    0.4744    0.4119     73951
weighted avg     0.4789    0.4288    0.3940     73951


Confusion Matrix
[[22134  8231]
 [34007  9579]]

ROC-AUC
0.6599856709035162

In [ ]:
# # 7. Feature Importance 확인

# rf = model.named_steps["clf"]

# feature_names = model.named_steps["preprocess"].get_feature_names_out()

# importance_df = pd.DataFrame({
#     "feature": feature_names,
#     "importance": rf.feature_importances_
# }).sort_values("importance", ascending=False)

# importance_df.head(30)

                                feature  importance
3                             num__hour    0.106530
7                         num__hour_cos    0.061186
6                         num__hour_sin    0.053349
42                   num__rest_cnt_500m    0.050201
43                  num__rest_cnt_1000m    0.038357
53       num__tour_food_mean_dist_k20_m    0.036078
85       num__subway_weighted_access_k5    0.025511
62            num__shop_mean_dist_k20_m    0.023320
41                   num__rest_cnt_300m    0.022890
86           num__subway_mean_dist_k5_m    0.022373
44             num__nearest_rest_dist_m    0.018529
13                   num__concert_total    0.018399
12                    num__gu_walk_area    0.017659
18                   num__concert_small    0.017419
15                 num__concert_private    0.017213
84           num__nearest_subway_dist_m    0.015837
2                               num__경도    0.015781
17                     num__concert_mid    0.014399
60             num__nearest_shop_dist_m    0.014187
14                  num__concert_public    0.014114
82                num__subway_cnt_1000m    0.014107
52  num__tour_food_weighted_density_k20    0.012816
71                   num__shop_type_cnt    0.012142
51        num__nearest_tour_food_dist_m    0.012012
45       num__rest_weighted_density_k20    0.011639
79               num__bus_stop_cnt_500m    0.011323
61       num__shop_weighted_density_k20    0.011312
76               num__bus_stop_cnt_300m    0.010940
73               num__shop_type_entropy    0.010751
46            num__rest_mean_dist_k20_m    0.010535

In [ ]:
# importance_df.to_csv("../DATA/PROCESS/feature_importance.csv")

In [5]:
import pandas as pd
import numpy as np

from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score


# =========================================================
# 1. 기본 세팅
# =========================================================

target_col = "target"

drop_cols = [
    target_col,
    "datetime",
]

drop_cols = [col for col in drop_cols if col in df.columns]

X = df.drop(columns=drop_cols)
y = df[target_col]

print("X shape:", X.shape)
print("\ny distribution:")
print(y.value_counts(normalize=True))


# =========================================================
# 2. 컬럼 타입 분리
# =========================================================

categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()
numeric_cols = X.select_dtypes(include=["int64", "float64", "int32", "float32"]).columns.tolist()

print("\nnumeric cols:", len(numeric_cols))
print("categorical cols:", len(categorical_cols))


# =========================================================
# 3. 전처리 파이프라인
# =========================================================

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    remainder="drop"
)


# =========================================================
# 4. Train/Test split
# =========================================================

print("\nTrain/Test split 진행 중...")

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\ntrain target distribution:")
print(y_train.value_counts(normalize=True))

print("\ntest target distribution:")
print(y_test.value_counts(normalize=True))


# =========================================================
# 5. 전처리 fit/transform
# =========================================================

print("\n전처리 fit_transform 진행 중...")

for _ in tqdm(range(1), desc="Preprocessing train"):
    X_train_proc = preprocessor.fit_transform(X_train)

print("\n전처리 transform 진행 중...")

for _ in tqdm(range(1), desc="Preprocessing test"):
    X_test_proc = preprocessor.transform(X_test)

print("X_train_proc shape:", X_train_proc.shape)
print("X_test_proc shape:", X_test_proc.shape)


# =========================================================
# 6. 모델 학습
# =========================================================

rf = RandomForestClassifier(
    n_estimators=300,
    random_state=42,
    class_weight="balanced",
    n_jobs=-1,
    verbose=1
)

print("\nRandomForest 학습 시작...")

for _ in tqdm(range(1), desc="Training RandomForest"):
    rf.fit(X_train_proc, y_train)


# =========================================================
# 7. 예측 및 평가
# =========================================================

print("\n예측 진행 중...")

for _ in tqdm(range(1), desc="Prediction"):
    y_pred = rf.predict(X_test_proc)
    y_proba = rf.predict_proba(X_test_proc)[:, 1]

print("\nClassification Report")
print(classification_report(y_test, y_pred, digits=4))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nROC-AUC")
print(roc_auc_score(y_test, y_proba))


# =========================================================
# 8. Feature Importance 추출
# =========================================================

print("\nFeature Importance 정리 중...")


# numeric feature names
feature_names = numeric_cols.copy()

# categorical one-hot feature names
if len(categorical_cols) > 0:
    onehot = preprocessor.named_transformers_["cat"].named_steps["onehot"]
    cat_feature_names = onehot.get_feature_names_out(categorical_cols).tolist()
    feature_names += cat_feature_names

importances = rf.feature_importances_

feature_importance_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
})

for _ in tqdm(range(1), desc="Sorting feature importance"):
    feature_importance_df = feature_importance_df.sort_values(
        by="importance",
        ascending=False
    ).reset_index(drop=True)

print("\nTop 30 Feature Importance")
print(feature_importance_df.head(30))


# =========================================================
# 9. 저장
# =========================================================

feature_importance_df.to_csv(
    "feature_importance_random_forest.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nfeature_importance_random_forest.csv 저장 완료")

X shape: (4033906, 97)

y distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

numeric cols: 95
categorical cols: 2

Train/Test split 진행 중...

/var/folders/g8/gwqmqng10_g3h7m8r02yq1qc0000gn/T/ipykernel_74879/2452497740.py:40: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object", "category"]).columns.tolist()

train target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

test target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

전처리 fit_transform 진행 중...

Preprocessing train: 100%|██████████| 1/1 [01:55<00:00, 115.84s/it]

전처리 transform 진행 중...

Preprocessing test: 100%|██████████| 1/1 [00:04<00:00,  4.12s/it]

X_train_proc shape: (3227124, 123)
X_test_proc shape: (806782, 123)

RandomForest 학습 시작...

Training RandomForest:   0%|          | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:   52.7s
[Parallel(n_jobs=-1)]: Done 180 tasks      | elapsed:  5.1min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  8.3min finished
Training RandomForest: 100%|██████████| 1/1 [08:21<00:00, 501.43s/it]

예측 진행 중...

Prediction:   0%|          | 0/1 [00:00<?, ?it/s][Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    1.7s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    9.3s
[Parallel(n_jobs=10)]: Done 300 out of 300 | elapsed:   15.2s finished
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    1.6s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    8.3s
[Parallel(n_jobs=10)]: Done 300 out of 300 | elapsed:   13.3s finished
Prediction: 100%|██████████| 1/1 [00:32<00:00, 32.38s/it]

Classification Report
              precision    recall  f1-score   support

           0     0.8771    0.8931    0.8850    408081
           1     0.8885    0.8719    0.8801    398701

    accuracy                         0.8826    806782
   macro avg     0.8828    0.8825    0.8826    806782
weighted avg     0.8827    0.8826    0.8826    806782


Confusion Matrix
[[364443  43638]
 [ 51072 347629]]

ROC-AUC
0.952918477061687

Feature Importance 정리 중...

Sorting feature importance: 100%|██████████| 1/1 [00:00<00:00, 70.73it/s]

Top 30 Feature Importance
                           feature  importance
0                             hour    0.156093
1                         hour_cos    0.092678
2                         hour_sin    0.075006
3                            month    0.047235
4                    rest_cnt_500m    0.033646
5                        month_sin    0.030322
6                   rest_cnt_1000m    0.028412
7                        month_cos    0.026744
8                    rest_cnt_300m    0.018656
9        tour_food_mean_dist_k20_m    0.015260
10          shop_mean_dist_k20_m_y    0.012866
11  tour_food_weighted_density_k20    0.012611
12                              경도    0.012223
13         subway_mean_dist_k5_m_x    0.012064
14          shop_mean_dist_k20_m_x    0.011849
15                         weekday    0.011591
16         subway_mean_dist_k5_m_y    0.011569
17                   rest_cnt_100m    0.010899
18                     weekday_sin    0.010894
19       nearest_subway_line_y_5호선    0.010804
20     subway_weighted_access_k5_y    0.010047
21           city_designated_total    0.009850
22               bus_stop_cnt_500m    0.009785
23               bus_stop_cnt_300m    0.009737
24                              위도    0.009608
25     subway_weighted_access_k5_x    0.009201
26       nearest_subway_line_x_5호선    0.009062
27        nearest_tour_food_dist_m    0.008984
28                    gu_walk_area    0.008711
29                 concert_private    0.008702

feature_importance_random_forest.csv 저장 완료

In [5]:
import pandas as pd
import numpy as np

from tqdm import tqdm

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import (
    RandomForestClassifier,
    ExtraTreesClassifier,
    GradientBoostingClassifier
)

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_auc_score,
    accuracy_score,
    f1_score
)


# =========================================================
# 1. 기본 세팅
# =========================================================

target_col = "target"

drop_cols = [
    target_col,
    "datetime",
]

drop_cols = [col for col in drop_cols if col in df.columns]

X = df.drop(columns=drop_cols)
y = df[target_col]

print("X shape:", X.shape)
print("\ny distribution:")
print(y.value_counts(normalize=True))


# =========================================================
# 2. 컬럼 타입 분리
# =========================================================

categorical_cols = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

numeric_cols = X.select_dtypes(
    include=["int64", "float64", "int32", "float32"]
).columns.tolist()

print("\nnumeric cols:", len(numeric_cols))
print("categorical cols:", len(categorical_cols))


# =========================================================
# 3. 전처리 파이프라인
# =========================================================

numeric_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore", sparse_output=False))
])

preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_cols),
        ("cat", categorical_transformer, categorical_cols),
    ],
    remainder="drop"
)


# =========================================================
# 4. Train/Test split
# =========================================================

print("\nTrain/Test split 진행 중...")

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\ntrain target distribution:")
print(y_train.value_counts(normalize=True))

print("\ntest target distribution:")
print(y_test.value_counts(normalize=True))


# =========================================================
# 5. 전처리 fit/transform
# =========================================================

print("\n전처리 fit_transform 진행 중...")

for _ in tqdm(range(1), desc="Preprocessing train"):
    X_train_proc = preprocessor.fit_transform(X_train)

print("\n전처리 transform 진행 중...")

for _ in tqdm(range(1), desc="Preprocessing test"):
    X_test_proc = preprocessor.transform(X_test)

print("X_train_proc shape:", X_train_proc.shape)
print("X_test_proc shape:", X_test_proc.shape)


# =========================================================
# 6. Feature name 정리
# =========================================================

feature_names = numeric_cols.copy()

if len(categorical_cols) > 0:
    onehot = preprocessor.named_transformers_["cat"].named_steps["onehot"]
    cat_feature_names = onehot.get_feature_names_out(categorical_cols).tolist()
    feature_names += cat_feature_names

print("\n전체 feature 개수:", len(feature_names))


# =========================================================
# 7. 모델 정의
# =========================================================

models = {
    "logistic_regression": LogisticRegression(
        max_iter=1000,
        class_weight="balanced",
        n_jobs=-1
    ),

    "random_forest": RandomForestClassifier(
        n_estimators=300,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1
    ),

    "extra_trees": ExtraTreesClassifier(
        n_estimators=300,
        random_state=42,
        class_weight="balanced",
        n_jobs=-1
    ),

    "gradient_boosting": GradientBoostingClassifier(
        random_state=42
    )
}


# =========================================================
# 8. 여러 모델 학습 및 평가
# =========================================================

results = []
feature_importance_dict = {}

for model_name, model in models.items():
    print("\n==============================")
    print(f"{model_name} 학습 시작")
    print("==============================")

    for _ in tqdm(range(1), desc=f"Training {model_name}"):
        model.fit(X_train_proc, y_train)

    print(f"\n{model_name} 예측 진행 중...")

    for _ in tqdm(range(1), desc=f"Prediction {model_name}"):
        y_pred = model.predict(X_test_proc)

        if hasattr(model, "predict_proba"):
            y_proba = model.predict_proba(X_test_proc)[:, 1]
            roc_auc = roc_auc_score(y_test, y_proba)
        else:
            y_proba = None
            roc_auc = np.nan

    acc = accuracy_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print("\nClassification Report")
    print(classification_report(y_test, y_pred, digits=4))

    print("\nConfusion Matrix")
    print(confusion_matrix(y_test, y_pred))

    print("\nROC-AUC")
    print(roc_auc)

    results.append({
        "model": model_name,
        "accuracy": acc,
        "f1_score": f1,
        "roc_auc": roc_auc
    })

    # =====================================================
    # Feature Importance 저장 가능한 모델만 처리
    # =====================================================

    if hasattr(model, "feature_importances_"):
        importances = model.feature_importances_

        feature_importance_df = pd.DataFrame({
            "feature": feature_names,
            "importance": importances
        }).sort_values(
            by="importance",
            ascending=False
        ).reset_index(drop=True)

        feature_importance_dict[model_name] = feature_importance_df

        print(f"\n{model_name} Top 30 Feature Importance")
        print(feature_importance_df.head(30))

        feature_importance_df.to_csv(
            f"feature_importance_{model_name}.csv",
            index=False,
            encoding="utf-8-sig"
        )

        print(f"\nfeature_importance_{model_name}.csv 저장 완료")


# =========================================================
# 9. 모델별 성능 비교 저장
# =========================================================

result_df = pd.DataFrame(results).sort_values(
    by="roc_auc",
    ascending=False
).reset_index(drop=True)

print("\n모델별 성능 비교")
print(result_df)

result_df.to_csv(
    "model_comparison_results.csv",
    index=False,
    encoding="utf-8-sig"
)

print("\nmodel_comparison_results.csv 저장 완료")

X shape: (4033906, 97)

y distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

numeric cols: 95
categorical cols: 2

Train/Test split 진행 중...

/var/folders/g8/gwqmqng10_g3h7m8r02yq1qc0000gn/T/ipykernel_24214/1302609549.py:53: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(

train target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

test target distribution:
target
0    0.505813
1    0.494187
Name: proportion, dtype: float64

전처리 fit_transform 진행 중...

Preprocessing train: 100%|██████████| 1/1 [02:42<00:00, 162.72s/it]

전처리 transform 진행 중...

Preprocessing test: 100%|██████████| 1/1 [00:04<00:00,  4.57s/it]

X_train_proc shape: (3227124, 123)
X_test_proc shape: (806782, 123)

전체 feature 개수: 123

==============================
logistic_regression 학습 시작
==============================

Training logistic_regression:   0%|          | 0/1 [00:00<?, ?it/s]/Users/carolyn/Desktop/study/SEOULDATA/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:1184: FutureWarning: 'n_jobs' has no effect since 1.8 and will be removed in 1.10. You provided 'n_jobs=-1', please leave it unspecified.
  warnings.warn(msg, category=FutureWarning)
/Users/carolyn/Desktop/study/SEOULDATA/.venv/lib/python3.14/site-packages/sklearn/linear_model/_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 1000 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=1000).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
Training logistic_regression: 100%|██████████| 1/1 [1:02:39<00:00, 3759.37s/it]

logistic_regression 예측 진행 중...

Prediction logistic_regression: 100%|██████████| 1/1 [00:01<00:00,  1.05s/it]

Classification Report
              precision    recall  f1-score   support

           0     0.8210    0.8302    0.8256    408081
           1     0.8242    0.8148    0.8194    398701

    accuracy                         0.8226    806782
   macro avg     0.8226    0.8225    0.8225    806782
weighted avg     0.8226    0.8226    0.8225    806782


Confusion Matrix
[[338773  69308]
 [ 73849 324852]]

ROC-AUC
0.9068662513130112

==============================
random_forest 학습 시작
==============================

Training random_forest: 100%|██████████| 1/1 [43:59<00:00, 2639.80s/it]

random_forest 예측 진행 중...

Prediction random_forest: 100%|██████████| 1/1 [00:34<00:00, 34.52s/it]

Classification Report
              precision    recall  f1-score   support

           0     0.8771    0.8931    0.8850    408081
           1     0.8885    0.8719    0.8801    398701

    accuracy                         0.8826    806782
   macro avg     0.8828    0.8825    0.8826    806782
weighted avg     0.8827    0.8826    0.8826    806782


Confusion Matrix
[[364443  43638]
 [ 51072 347629]]

ROC-AUC
0.952918477061687

random_forest Top 30 Feature Importance
                           feature  importance
0                             hour    0.156093
1                         hour_cos    0.092678
2                         hour_sin    0.075006
3                            month    0.047235
4                    rest_cnt_500m    0.033646
5                        month_sin    0.030322
6                   rest_cnt_1000m    0.028412
7                        month_cos    0.026744
8                    rest_cnt_300m    0.018656
9        tour_food_mean_dist_k20_m    0.015260
10          shop_mean_dist_k20_m_y    0.012866
11  tour_food_weighted_density_k20    0.012611
12                              경도    0.012223
13         subway_mean_dist_k5_m_x    0.012064
14          shop_mean_dist_k20_m_x    0.011849
15                         weekday    0.011591
16         subway_mean_dist_k5_m_y    0.011569
17                   rest_cnt_100m    0.010899
18                     weekday_sin    0.010894
19       nearest_subway_line_y_5호선    0.010804
20     subway_weighted_access_k5_y    0.010047
21           city_designated_total    0.009850
22               bus_stop_cnt_500m    0.009785
23               bus_stop_cnt_300m    0.009737
24                              위도    0.009608
25     subway_weighted_access_k5_x    0.009201
26       nearest_subway_line_x_5호선    0.009062
27        nearest_tour_food_dist_m    0.008984
28                    gu_walk_area    0.008711
29                 concert_private    0.008702

feature_importance_random_forest.csv 저장 완료

==============================
extra_trees 학습 시작
==============================

Training extra_trees: 100%|██████████| 1/1 [10:27<00:00, 627.04s/it]

extra_trees 예측 진행 중...

Prediction extra_trees: 100%|██████████| 1/1 [00:41<00:00, 41.32s/it]

Classification Report
              precision    recall  f1-score   support

           0     0.8783    0.8913    0.8848    408081
           1     0.8871    0.8736    0.8803    398701

    accuracy                         0.8826    806782
   macro avg     0.8827    0.8825    0.8825    806782
weighted avg     0.8826    0.8826    0.8826    806782


Confusion Matrix
[[363733  44348]
 [ 50383 348318]]

ROC-AUC
0.9526016728363075

extra_trees Top 30 Feature Importance
                           feature  importance
0                             hour    0.130623
1                         hour_cos    0.119275
2                         hour_sin    0.084916
3                            month    0.039551
4                        month_sin    0.034433
5                        month_cos    0.029506
6                    rest_cnt_500m    0.022836
7        nearest_subway_line_x_5호선    0.014380
8        nearest_subway_line_y_5호선    0.014153
9                   rest_cnt_1000m    0.012434
10                   rest_cnt_300m    0.011675
11                     concert_mid    0.010670
12                  concert_public    0.010170
13              tour_food_cnt_300m    0.009206
14  tour_food_weighted_density_k20    0.008344
15                         weekday    0.008301
16              subway_cnt_1000m_y    0.008108
17                     weekday_sin    0.007960
18          shop_mean_dist_k20_m_y    0.007762
19               subway_cnt_300m_x    0.007619
20                    gu_walk_area    0.007581
21               subway_cnt_300m_y    0.007483
22              subway_cnt_1500m_y    0.007054
23               bus_stop_cnt_100m    0.007020
24              subway_cnt_1500m_x    0.007002
25     shop_weighted_density_k20_y    0.006784
26          shop_mean_dist_k20_m_x    0.006773
27         subway_mean_dist_k5_m_x    0.006750
28     shop_weighted_density_k20_x    0.006694
29               bus_stop_cnt_300m    0.006677

feature_importance_extra_trees.csv 저장 완료

==============================
gradient_boosting 학습 시작
==============================

Training gradient_boosting: 100%|██████████| 1/1 [1:05:22<00:00, 3922.02s/it]

gradient_boosting 예측 진행 중...

Prediction gradient_boosting: 100%|██████████| 1/1 [00:08<00:00,  8.17s/it]

Classification Report
              precision    recall  f1-score   support

           0     0.8485    0.8728    0.8605    408081
           1     0.8659    0.8405    0.8530    398701

    accuracy                         0.8568    806782
   macro avg     0.8572    0.8566    0.8567    806782
weighted avg     0.8571    0.8568    0.8568    806782


Confusion Matrix
[[356162  51919]
 [ 63585 335116]]

ROC-AUC
0.9325624609273735

gradient_boosting Top 30 Feature Importance
                           feature  importance
0                             hour    0.168857
1                    rest_cnt_500m    0.114873
2                   rest_cnt_1000m    0.090770
3                         hour_cos    0.054558
4                bus_stop_cnt_300m    0.042770
5                   movie_seat_cnt    0.035897
6                               경도    0.033769
7            city_designated_total    0.029414
8        nearest_subway_line_x_5호선    0.028103
9      subway_weighted_access_k5_x    0.027385
10                        hour_sin    0.026462
11       nearest_subway_line_y_5호선    0.020141
12                           month    0.019792
13                   concert_total    0.018344
14          shop_mean_dist_k20_m_x    0.017653
15  tour_food_weighted_density_k20    0.017090
16               bus_stop_cnt_500m    0.015520
17                   rest_cnt_300m    0.015513
18             nearest_rest_dist_m    0.014147
19      tangible_cultural_property    0.013079
20         subway_mean_dist_k5_m_x    0.012303
21         subway_mean_dist_k5_m_y    0.011767
22          shop_mean_dist_k20_m_y    0.011337
23               bus_stop_cnt_100m    0.011033
24                              위도    0.010248
25         nearest_subway_dist_m_x    0.009967
26                   rest_cnt_100m    0.009407
27                       month_cos    0.008689
28            rest_mean_dist_k20_m    0.007544
29              subway_cnt_1500m_y    0.007313

feature_importance_gradient_boosting.csv 저장 완료

모델별 성능 비교
                 model  accuracy  f1_score   roc_auc
0        random_forest  0.882608  0.880109  0.952918
1          extra_trees  0.882582  0.880294  0.952602
2    gradient_boosting  0.856834  0.852999  0.932562
3  logistic_regression  0.822558  0.819443  0.906866

model_comparison_results.csv 저장 완료